### ISSUE TITLE
Feature: allow changing color of chart lines

### ISSUE THREAD

**Issue by crabdancing** [hiltonm/dioxus-charts#14]
Unless I'm missing something, charts like `LineChart` hardcode the color of the lines. Seems like it would be quite easy to make it user-configurable.

**Comment by H12M54AM** [comment]
So true

**Comment by jmriesen** [comment]
I found that you can use CSS to override the line colors.
I set the property class_line to "line" and then added the folowing css
```css
.line-0{
    & path{
        stroke:red;
    }
}
.line-1{
    & path{
        stroke:blue;
    }
}
.line-2{
    & path{
        stroke:orange;
    }
}
```
